name: "PM2 Deploy"
on:
  push:
    branches: [ production ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #
      # ... your other steps, such as running tests, etc...
      #
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy.key
          sudo chmod 600 ~/.ssh/deploy.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}

      - name: Install PM2
        run: sudo npm i pm2 -g

      - name: Deploy
        run: |
          pm2 deploy ecosystem.config.js production
          env
        env: 
          S_DB_URL: ${{ secrets.DB_URL }}
          S_SHORT_URL: ${{ secrets.SHORT_URL }}
          S_PORT: ${{ secrets.PORT }}
          S_HOST: ${{ secrets.HOST }}
        # Or alternately, put this deploy script in your package.json's scripts and run it using yarn/npm:
        # run: yarn deploy
